services:
  - type: web
    name: ledo-sports-academy
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ENABLE_MONITORING
        value: false
      - key: MONITOR_PORT
        value: 3001
    autoDeploy: true